# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: ./test.sh
    displayName: 'Run Test Cases'

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: ./test.sh
    displayName: 'Run Test Cases'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python .\duplicate_check.py 8086asm .\test_a .\test_b
    displayName: 'Run 8086asm Test Cases'
  - script: .\duplicate_check.py c .\test_a .\test_b
    displayName: 'Run c Test Cases'
  - script: .\duplicate_check.py c++ .\test_a .\test_b
    displayName: 'Run c++ Test Cases'
  - script: .\duplicate_check.py java .\test_a .\test_b
    displayName: 'Run java Test Cases'
  - script: .\duplicate_check.py lisp .\test_a .\test_b
    displayName: 'Run lisp Test Cases'
  - script: .\duplicate_check.py m2 .\test_a .\test_b
    displayName: 'Run m2 Test Cases'
  - script: .\duplicate_check.py miranda .\test_a .\test_b
    displayName: 'Run miranda Test Cases'
  - script: .\duplicate_check.py pascal .\test_a .\test_b
    displayName: 'Run pascal Test Cases'
  - script: .\duplicate_check.py text .\test_a .\test_b
    displayName: 'Run plain text Test Cases'