.\duplicate_check.py 8086asm .\test_a .\test_b
.\duplicate_check.py c .\test_a .\test_b
.\duplicate_check.py c++ .\test_a .\test_b
.\duplicate_check.py java .\test_a .\test_b
.\duplicate_check.py lisp .\test_a .\test_b
.\duplicate_check.py m2 .\test_a .\test_b
.\duplicate_check.py miranda .\test_a .\test_b
.\duplicate_check.py pascal .\test_a .\test_b
.\duplicate_check.py text .\test_a .\test_b